/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GerenciaControladoras;
import Model.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class TelaDeLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeLogin
     */
    public TelaDeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoDeLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoDeSenha = new javax.swing.JPasswordField();
        botaoDeEntrar = new javax.swing.JButton();
        BotaoDeCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DE LOGIN");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("LOGIN");

        campoDeLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("SENHA");

        campoDeSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botaoDeEntrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        botaoDeEntrar.setText("ENTRAR");
        botaoDeEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoDeEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeEntrarActionPerformed(evt);
            }
        });

        BotaoDeCadastro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BotaoDeCadastro.setText("FAZER CADASTRO");
        BotaoDeCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotaoDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(campoDeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(BotaoDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(botaoDeEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botaoDeEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BotaoDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void botaoDeEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeEntrarActionPerformed

        String login = campoDeLogin.getText();
        String senha = String.valueOf(campoDeSenha.getPassword());

        try {
            GerenciaControladoras gerenciaControladoras = new GerenciaControladoras();
            Pessoa pessoaLogada = gerenciaControladoras.fazLogin(login, senha);

            if (pessoaLogada != null) {
                JOptionPane.showMessageDialog(null, "Login Realizado Com Sucesso!" + "\n"
                        + "Logado Como: " + pessoaLogada.getTipoUsuario());
                limparCamposDeLogin();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario Nao Enconrado / Inexistente!");
                limparCamposDeLogin();
            }

            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Erro Ao Fazer Login");
        }

       
    }//GEN-LAST:event_botaoDeEntrarActionPerformed

    private void BotaoDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeCadastroActionPerformed

        TelaDeCadastro telaDeCadastro = new TelaDeCadastro();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_BotaoDeCadastroActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin().setVisible(true);
            }
        });
    }

    public void exibirTelaDeLogin() {

    }

    public void limparCamposDeLogin() {
        campoDeLogin.setText("");
        campoDeSenha.setText("");
    }

    public void exibirMensagemDeErroNoLogin() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDeCadastro;
    private javax.swing.JButton botaoDeEntrar;
    private javax.swing.JTextField campoDeLogin;
    private javax.swing.JPasswordField campoDeSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
